Trait {
	#name : #ZESpatialPhagy,
	#traits : 'ZESpatialPhage + ZESpatialAppearPhage + ZESpatialCaressPhage + ZESpatialMovePhage + ZESpatialPressurePhage + ZESpatialHardenPhage + ZESpatialSoftenPhage + ZESpatialVanishPhage',
	#classTraits : 'ZESpatialPhage classTrait + ZESpatialAppearPhage classTrait + ZESpatialCaressPhage classTrait + ZESpatialMovePhage classTrait + ZESpatialPressurePhage classTrait + ZESpatialHardenPhage classTrait + ZESpatialSoftenPhage classTrait + ZESpatialVanishPhage classTrait',
	#category : #'Zeugma-Events'
}
